GET http://localhost:3000/

###
GET http://localhost:3000/request-type

###
GET http://localhost:3000/public/

###
GET http://localhost:3000/users/1

###
GET http://localhost:3000/search?keyName=node-express

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
User-Agent: Mozilla/5.0
Authorization: token xxxx

{
    "email": "hsimpson@mail.com",
    "password": "123456"
}

###
GET http://localhost:3000/anatomy?filter=bones

###
GET http://localhost:3000/home

###
GET http://localhost:3000/res-test

###
GET http://localhost:3000/index

###
GET http://localhost:3000/indexFile


